### PR TITLE
Audio: Fix build

### PR DESCRIPTION
**Pull request by dmd79**

### CODE REVIEW

**Comment by smeroni68** [comment]
Hi Davide,
can you give details or a description for these commits? What they fix, to be clear. Thanks.

**Comment by dmd79** [comment]
I'm sorry, but seems that Bruno Martins <bgcngm@gmail.com> make it first
https://review.lineageos.org/#/c/195914/
Here you can find explaination

**Comment by B--B** [comment]
Hi there, big thanks for this, i will backport in old branch too, i'm actually use that branch for working audio in 8.1 dp, still misses some CAF changes from frameworks

**Comment by dmd79** [comment]
It works fine for zuk z2 plus
Unfortunately still no working for zuk z2 pro because it have lib audio amplifier. Already add amplifier commit but no luck
https://github.com/LineageOS/android_hardware_qcom_audio/commit/26e63da107ca49c566f1d9c38feb245f966aa6ae

**Comment by smeroni68** [comment]
Hi Davide, are you compiling our code for your devices?

**Comment by dmd79** [comment]
Yes, but only for testing r25
I'm the z2 maintainer for aex

**Comment by smeroni68** [comment]
Thanks for info, you are welcome here... and any help on developing is appreciated!!

**Pull request merged**
